import { ColorPalette, FridayAppTheme } from 'interfaces/theme';

const colorPalette: ColorPalette = {
  primaryBlue20: '#F1F6FE',
  primaryBlue40: '#D0E2FC',
  primaryBlue60: '#146CF0',
  friBlueBorder: '#BCD0EC',
  green20: '#F1F8F4',
  green40: '#D1E7DA',
  green60: '#178746',
  navy40: '#CDD0D8',
  navy60: '#04143A',
  gold40: '#FDEBD2',
  gold60: '#F39C1E',
  brandOrange20: '#146CF0',
  brandOrange40: '#FFDBCC',
  brandOrange60: '#FF4C00',
  red20: '#FEF0F0',
  red40: '#FBCDCD',
  red60: '#E90606',
  darkBrown40: '#CDD0D8',
  darkBrown60: '#231F20',
  baseGray10: '#F5F5F5',
  baseGray20: '#E1E4E5',
  baseGray40: '#C6C7CA',
  baseGray80: '#676B75',
  baseGray100: '#383D4A',
  baseWarning: '#FDCA40',
  baseWhite: '#ffffff',
  lightRed: '#E906060F',
  lightOrange: '#FF4C000F',
  lightBlue: '#146CF010',
  lightGreen: '#1787460F',
  lightGrey: '#04143A0F',
};

const fridayAppTheme: FridayAppTheme = {
  Success: colorPalette.green60,
  Error: colorPalette.red60,
  Warning: colorPalette.baseWarning,
  Primary: {
    brand: colorPalette.primaryBlue60,
    main: colorPalette.baseWhite,
  },
  Secondary: {
    brand: colorPalette.baseWhite,
    main: colorPalette.primaryBlue60,
  },
  Text: {
    primary: colorPalette.navy60,
    main: colorPalette.baseGray100,
    secondary: colorPalette.baseGray80,
    light: colorPalette.baseWhite,
    info: colorPalette.primaryBlue60,
    success: colorPalette.green60,
    disabled: colorPalette.baseGray40,
    error: colorPalette.red60,
    orange: colorPalette.brandOrange60,
  },
  Link: colorPalette.primaryBlue60,
  Background: {
    main: colorPalette.baseGray10,
    primary: colorPalette.baseWhite,
    secondary: colorPalette.primaryBlue60,
    lightBlue: colorPalette.primaryBlue20,
    orange: colorPalette.brandOrange60,
    info: colorPalette.lightBlue,
    baseGray20: colorPalette.baseGray20,
    baseGray100: colorPalette.baseGray100,
  },
  colorCombinations: {
    orange: {
      background: colorPalette.lightOrange,
      text: colorPalette.brandOrange60,
    },
    red: {
      background: colorPalette.lightRed,
      text: colorPalette.red60,
    },
    blue: {
      background: colorPalette.lightBlue,
      text: colorPalette.primaryBlue60,
    },
    green: {
      background: colorPalette.lightGreen,
      text: colorPalette.green60,
    },
    grey: { background: colorPalette.lightGrey, text: colorPalette.navy60 },
  },
  BoxShadow: {
    light: colorPalette.baseGray40,
    dark: '#171717',
    navBar: colorPalette.baseGray100,
  },
  Icons: {
    friPrimary: colorPalette.primaryBlue60,
    primaryBlue40: colorPalette.primaryBlue40,
    friBlueBorder: colorPalette.friBlueBorder,
    friDecorativeOne: colorPalette.navy60,
    friDecorativeTwo: colorPalette.brandOrange60,
    baseWarning: colorPalette.baseWarning,
    baseSuccess: colorPalette.green60,
    baseWhite: colorPalette.baseWhite,
    baseError: colorPalette.red60,
    baseGray100: colorPalette.baseGray100,
    baseGray80: colorPalette.baseGray80,
    baseGray40: colorPalette.baseGray40,
    baseGray20: colorPalette.baseGray20,
    baseGray10: colorPalette.baseGray10,
    lightRed: colorPalette.lightRed,
    lightOrange: colorPalette.lightOrange,
    lightBlue: colorPalette.lightBlue,
    lightGreen: colorPalette.lightGreen,
    green40: colorPalette.green40,
    lightGrey: colorPalette.lightGrey,
    gold60: colorPalette.gold60,
    gold40: colorPalette.gold40,
  },
  Lines: {
    baseGray10: colorPalette.baseGray10,
    divider: colorPalette.baseGray20,
    input: colorPalette.baseGray40,
    friBlueBorder: colorPalette.friBlueBorder,
  },
};

export default fridayAppTheme;
